version: '3'

services:
  www:
    build: app
    container_name: www_docker_symfony
    ports:
      - "8080:80"
    volumes:
        - ./app/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-intisar}
      PGDATA: /data/postgres
    volumes:
       - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: intisar
    ports:
      - "5050:80"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
